remote_theme: pages-themes/minimal@v0.2.0

plugins:
  - jekyll-remote-theme

title: SurfelPlus
description: A real time dynamic global illumination renderer based on surfel. Final project of University of Pennsylvania's CIS 565 GPU Programming and Architecture class. Written by Zhen Ren, Ruipeng Wang and Jinxiang Wang.
logo: /img/PennEngineeringLogo.png
show_downloads: true